mywebsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
]

# if settings.DEBUG:
#    urlpatterns += static(settings.STATIC_URL)

products/urls.py
from django.urls import path

from products.views import auth
from products.views import cart
from products.views import index


app_name = 'products'
urlpatterns = [
    path('', index.index, name="index"),
    path('register/', auth.register, name="register"),
    path('login/', auth.login_user, name="login"),
    path('logout/', auth.logout_user, name='logout'),
    path('<int:product_id>/cart', cart.user_cart_add, name="cart_add"),
    path('user/cart', cart.UserCartListView.as_view(), name="cart"),
    path('user/cart/<int:pk>/delete', cart.UserCartDeleteView.as_view(), name='cart_delete'),
    path('user/cart/<int:pk>/update', cart.UserCartUpdateView.as_view(), name='cart_update'),
    path('user/<uuid:uuid>/', auth.verify, name='verify')
]

products/models/cart.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from .product import Book


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + "'s cart"


@receiver(post_save, sender=User)
def create_user_cart(sender, instance, created, **kwargs):
    if created:
        Cart.objects.create(user=instance)


class CartElement(models.Model):
    product = models.ForeignKey(Book, on_delete=models.CASCADE)
    count = models.IntegerField(default=1)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.product) + ': ' + str(self.count)

    def increase(self, count):
        self.count += count
        self.save()

products/models/message.py
from django.contrib.auth.models import User
from django.db import models


class MessageWrapper(models.Model):
    text = models.CharField(max_length=255)
    sent_date = models.DateField()
    addressee = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text

products/models/product.py
from django.db import models


class Product(models.Model):
    # code = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    cost = models.FloatField()
    stock = models.IntegerField()
    image = models.CharField(max_length=100)
    # cart = models.ManyToManyField(Cart, on_delete=models.CASCADE)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Book(Product):
    author = models.CharField(max_length=255, default='')
    page_count = models.IntegerField()

products/models/user.py
import uuid

from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.urls import reverse

#from products.tasks import send_verification_email


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    has_unread_message = models.BooleanField(name='verified', default=False)
    verification_uuid = models.UUIDField(default=uuid.uuid4)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    instance.userprofile.save()


# @receiver(post_save, sender=User)
# def user_post_save(sender, instance, signal, *args, **kwargs):
#     if not instance.userprofile.verified:
#         offset = reverse("products:verify", kwargs={"uuid": str(instance.userprofile.verification_uuid)})
#         # send_mail('Verify your account',
#         #           'Follow this link to verify your account: '
#         #           f'http://localhost:8000{offset}',
#         #           'Luckstriker073@gmail.com',
#         #           [instance.email],
#         #           fail_silently=False,
#         #           )
#         #send_verification_email.delay()

products/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required field')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


def validate_date(value):
    if value is not None:
        return True


class MessageForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.EmailField(widget=forms.EmailInput)
    text = forms.CharField(widget=forms.Textarea)
    date = forms.DateField(required=True, widget=forms.DateInput(attrs={'type': 'date'}), localize=True)

products/views/cart.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import UpdateView, DeleteView, ListView

from products.models.cart import CartElement
from products.models.product import Book

import logging
logger = logging.getLogger(__name__)


@method_decorator(login_required, name='dispatch')
class UserCartUpdateView(UpdateView):
    model = CartElement
    template_name = 'products/update.html'
    success_url = reverse_lazy('products:cart')
    fields = ('count',)


@method_decorator(login_required, name='dispatch')
class UserCartDeleteView(DeleteView):
    model = CartElement
    template_name = 'products/delete.html'
    success_url = reverse_lazy('products:cart')

    # Overriding dispatch to avoid 404,
    # if user clicks prev page button
    def dispatch(self, request, *args, **kwargs):
        try:
            cart_element = CartElement.objects.get(id=kwargs['pk'])
            if request.method == 'GET':
                return super().dispatch(request, args, kwargs)
            else:
                cart_element.delete()
                return redirect(self.success_url)
        except CartElement.DoesNotExist:
            return redirect(self.success_url)


@method_decorator(login_required, name='dispatch')
class UserCartListView(ListView):
    model = CartElement

    def dispatch(self, request, *args, **kwargs):
        user = User.objects.get(id=request.user.id)
        products = user.cart.cartelement_set
        return render(request, 'products/cart.html', {'user': user, 'cart_elements': products})


@login_required
def user_cart_add(request, product_id):
    user = User.objects.get(id=request.user.id)
    try:
        product = Book.objects.get(id=product_id)
    except Book.DoesNotExist:
        logging.error('Book.DoesNotExist')
        raise Http404('No such book in the query')
    try:
        user.cart.cartelement_set.get(product=product)
    except CartElement.DoesNotExist:
        cart_element = CartElement.objects.create(product=product, cart=user.cart)
    products = user.cart.cartelement_set
    logger.debug(f'{user.username}\'s cart: {products.all()}')
    return redirect('products:cart')

products/views/index.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views.generic import ListView

from products.models.message import MessageWrapper
from products.models.product import Book

import logging
logger = logging.getLogger(__name__)


@login_required
def index(request):
    books = Book.objects.all()
    logger.debug(books)
    context = {'books': books}
    return render(request, 'products/index.html', context)

products/templates/products/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>
  <body>
    {% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <div class="navbar-collapse collapse text-right" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'products:index' %}">Home</a>
          </li>
        </ul>
      </div>
          <span class="user" style="color: aliceblue; padding-right: 50px">
          {% if request.user.is_authenticated %}
            Welcome, {{ request.user.username }}
          {% endif %}
      </span>
      <span class="user" style="color: aliceblue;">
          {% if request.user.is_authenticated %}
              <a style="color: lightyellow;padding-left: 10px" href="{% url 'products:logout' %}">Logout</a>
              <a style="color: lightyellow;padding-left: 10px" href="{% url 'products:cart' %}">Cart</a>
          {% endif %}
      </span>
    </div>
  </nav>
        <p></p>
  {% endblock %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

products/templates/products/cart.html
{% extends 'products/base.html' %}

{% block content %}
    <p>{{ user.username }}'s Cart</p>
    <table class="table">
        <tr>
            <thead class="thead-light">
                <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Quantity</th>
                    <th scope="col"></th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for element in cart_elements.all %}
                    <tr>
                        <td style="padding-top: 20px">{{ element.product.name }}</td>
                        <td style="padding-top: 20px">{{ element.count }}</td>
                        <td><a href="{% url 'products:cart_update' element.id %}" class="btn btn-success">Update</a></td>
                        <td><a href="{% url 'products:cart_delete' element.id %}" class="btn btn-danger">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </tr>
    </table>


{% endblock %}

products/templates/products/delete.html
{% extends 'products/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Delete # {{ object.product.name }}</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="alert alert-warning" role="alert">
                    Are you sure you want to delete {{ object.product.name }}?
                </div>
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
        </div>
    </div>
{% endblock %}

products/templates/products/index.html
{% extends 'products/base.html' %}
{% load static %}


{% block content %}
    <h1>Books</h1>
    <div class="row">
        {% for book in books %}
            <div class="col">
            <div class="card" style="width: 18rem;">
                {% static "" as baseUrl %}
                <img width="40px" height="400px" src="{{ baseUrl }}products/images/{{ book.image }}" class="card-img-top" alt="img">
                <div class="card-body">
                    <div >
                        <h5 class="card-title" style="float: left">{{ book.name }}</h5>
                        <p class="card-text" align="right">{{ book.page_count }} pages</p>
                    </div>
                    <hr/>
                    <h5 class="card-title">{{ book.author }}</h5>
                    <p class="card-text">${{ book.cost }}</p>
                    <form action="{% url 'products:cart_add' book.id %}" method="post">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-primary" value="Add to Cart">
                    </form>

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

products/templates/products/login.html
{% extends 'products/base.html' %}

{% block content %}
    <h1>Log-in</h1>
    <p>Please, log in</p>
    {% if data %}
        <p style="color: red">{{ data }}</p>
    {% endif %}
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log-in"></p>
        <a href="{% url 'products:register' %}"><input type="button" value="Register"></a>
        <input type="hidden" name="next" value="{{ request.GET.next }}"/>
    </form>
{% endblock %}

products/templates/products/message.html
{% extends 'admin/change_form.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <div class="submit-row">
        <input type="submit" value="Send"/>
    </div>
    </form>
{% endblock %}

products/templates/products/register.html
{% extends 'products/base.html' %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create account"></p>
    </form>
{% endblock %}

products/templates/products/update.html
{% extends 'products/base.html' %}

{% block content %}
    <div class="card">
        <div class="card-header">
            <h5 class="card-title">Update # {{ object.product.name }}</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Update</button>
            </form>
        </div>
    </div>
{% endblock %}

products/templates/products/user_registered.html
{% extends "products/base.html" %}

{% block content %}
    <h1>Welcome, {{ new_user.username }}</h1>
    <p>Your account has been successfully created. Now you can <a href="{% url "products:login" %}">log in</a>.</p>
{% endblock %}